#  Introducción a NumPy 
¿Qué es NumPy?

- Biblioteca para Python que permite realizar cálculos matemáticos y operaciones sobre arrays de manera eficiente.
- Está implementado en C y Fortran, lo que lo hace muy rápido comparado con las listas de Python.
- Base para otras bibliotecas como Pandas, Scikit-Learn y TensorFlow.

Installacion: 

`pip install numpy`

Importación: 

```python 
import numpy as np 
```
por convenio se suele usar el alias para acortar su nombre

In [1]:
import numpy as np 

In [2]:
my_list = list(range(100000000)) # Utilizando Listas Python
%time my_list2 = [x * 2 for x in my_list]

CPU times: total: 6.28 s
Wall time: 6.28 s


In [3]:
my_arr = np.arange(100000000)  # Utilizando NumPy Arrays
%time my_arr2 = my_arr * 2

CPU times: total: 266 ms
Wall time: 281 ms


## Creación de Arrays
### crear un array desde una lista o tupla

In [4]:
import numpy as np 
arr = np.array([1, 2, 3, 4])
print(arr)


[1 2 3 4]


### Crear un array de ceros, unos o valores aleatorio

In [23]:
# np.random.seed(1)  # Semilla para reproducibilidad
print(np.zeros((3, 4)))   # Array 3x4 de ceros
print(np.ones((2, 3)))    # Array 2x3 de unos
print(np.random.rand(4))  # Array con 4 valores aleatorios entre 0 y 1


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0.16983042 0.8781425  0.09834683 0.42110763]


###  Crear un array con valores en un rango o espacio lineal

In [24]:
print(np.arange(0, 10, 2))      # [0 2 4 6 8]
print(np.linspace(0, 1, 5))     # [0.  0.25 0.5  0.75 1. ]

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


## Propiedades de los Arrays 

In [ ]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

print(arr.shape)   # (2, 3) → dimensión del array
print(arr.size)    # 6 → número total de elementos
print(arr.ndim)    # 2 → número de dimensiones
print(arr.dtype)   # int64 → tipo de datos
print(arr.itemsize) # 8 → tamaño en bytes de cada elemento
print(arr.nbytes)   # 48 → tamaño total en bytes del array


(2, 3)
6
2
int64
8
48


2

## Indexación y Slicing

In [29]:
arr = np.array([10, 20, 30, 40])
print(arr[1])   # 20
print(arr[1:3]) # [20 30]
print(arr[::2]) # [10 30]
print(arr[::-1]) # [40 30 20 10]

20
[20 30]
[10 30]
[40 30 20 10]


In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 1])  # 2
print(arr[:, 1])  # [2 5] → segunda columna
print(arr[1, :])  # [4 5 6] → segunda fila
print(arr[0, 1:]) # [2 3] → primera fila, desde la segunda columna en adelante

2
[2 5]
[4 5 6]
[2 3]


## Operaciones Matemáticas
### Operaciones básicas

In [31]:
arr = np.array([1, 2, 3, 4])
print(arr + 2)      # [3 4 5 6]
print(arr * 3)      # [3 6 9 12]
print(arr ** 2)     # [1 4 9 16]
print(arr % 3)      # [1 2 0 1]

[3 4 5 6]
[ 3  6  9 12]
[ 1  4  9 16]
[1 2 0 1]


### Producto punto

In [33]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))  # 32 → (1*4 + 2*5 + 3*6)


32


### operacion matriz por matriz

In [39]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
a = np.random.randint(0, 10, (100, 100))
b = np.random.randint(0, 10, (100, 100))
print(a @ b)  # [[19 22] [43 50]] → producto matricial a*b fila por columna


[[1549 1944 1937 ... 1845 1632 1728]
 [1845 2280 2114 ... 1933 1571 1994]
 [1540 1923 1833 ... 1844 1699 1740]
 ...
 [1823 2262 2047 ... 2080 1834 1848]
 [1778 2105 1901 ... 1944 1712 1797]
 [2037 2282 2086 ... 2163 1783 2156]]


### mas operaciones
| Tipo | Operación | Descripción |
|:---------|:-----|:-----|
| Unario | *abs* | Valor absoluto de cada elemento |
| | *sqrt* | Raíz cuadrada de cada elemento |
| | *exp* | e^x, siendo x cad elemento |
| | *log, log10, log2* | Logaritmos en distintas bases de cada elemento |
| | *sign* | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| | *ceil* | Redondea cada elemento por arriba |
| | *floor* | Redondea cada elemento por abajo |
| | *isnan* | Retorna si cada elemento es Nan |
| | *cos, sin, tan* | Operaciones trigonométricas en cada elemento |
| | *arccos, arcsin, arctan* | Inversas de operaciones trigonométricas en cada elemento |
| Binario | *add* | Suma de dos arrays |
| | *substract* | Resta de dos arrays |
| | *multiply* | Multiplicación de dos arrays |
| | *divide* | División de dos arrays |
| | *maximum, minimum* | Retorna el valor máximo/mínimo de cada pareja de elementos |
| | *equal, not_equal* | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | *greater, greater_equal, less, less_equal* | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

### Estadistica



In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr.mean())   # 2.5 → media
print(arr.std())    # 1.118033988749895 → desviación estándar
print(arr.sum())    # 10 → suma
print(arr.min())    # 1 → mínimo
print(arr.max())    # 4 → máximo


2.5
1.118033988749895
10
1
4


## Funciones Útiles de NumPy
- `np.exp` → exponencial
- `np.log` → logaritmo natural
- `np.sin`, `np.cos`, `np.tan` → funciones trigonométricas
- `np.arcsin`, `np.arccos`, `np.arctan` → funciones trigonométricas inversas
- `np.sinh`, `np.cosh`, `np.tanh` → funciones hiperbólicas
- `np.arcsinh`, `np.arccosh`, `np.arctanh` → funciones hiperbólicas inversas
- `np.sqrt` → raiz

In [38]:
arr = np.array([1, 2, 3, 4])
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.sort(arr))          # ordena el array [1 2 3 4]
print(np.argsort(arr))       # [0 1 2 3] → índices que ordenan el array
print(np.argmax(arr))        # 3 → índice del valor máximo
print(np.argmin(arr))        # 0 → índice del valor mínimo
print(np.where(arr > 2))     # (array([2, 3]),) → posiciones donde se cumple la condición
print(np.unique(arr))        # [1 2 3 4] → valores únicos
print(np.bincount(arr))      # [0 1 1 1 1] → cuenta de ocurrencias de cada valor
print(np.concatenate((a, b))) # [[1 2] [3 4] [5 6] [7 8]] → concatenación de arrays
print(np.vstack((a, b)))      # [[1 2] [3 4] [5 6] [7 8]] → apilado vertical
print(np.hstack((a, b)))      # [1 2 3 4 5 6 7 8] → apilado horizontal



[1 2 3 4]
[0 1 2 3]
3
0
(array([2, 3]),)
[1 2 3 4]
[0 1 1 1 1]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


## Cosas varias mas
### Operadores unarios y binarios

| Tipo | Operación | Descripción |
|:---------|:-----|:-----|
| Unario | *abs* | Valor absoluto de cada elemento |
| | *sqrt* | Raíz cuadrada de cada elemento |
| | *exp* | e^x, siendo x cad elemento |
| | *log, log10, log2* | Logaritmos en distintas bases de cada elemento |
| | *sign* | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
| | *ceil* | Redondea cada elemento por arriba |
| | *floor* | Redondea cada elemento por abajo |
| | *isnan* | Retorna si cada elemento es Nan |
| | *cos, sin, tan* | Operaciones trigonométricas en cada elemento |
| | *arccos, arcsin, arctan* | Inversas de operaciones trigonométricas en cada elemento |
| Binario | *add* | Suma de dos arrays |
| | *substract* | Resta de dos arrays |
| | *multiply* | Multiplicación de dos arrays |
| | *divide* | División de dos arrays |
| | *maximum, minimum* | Retorna el valor máximo/mínimo de cada pareja de elementos |
| | *equal, not_equal* | Retorna la comparación (igual o no igual) de cada pareja de elementos |
| | *greater, greater_equal, less, less_equal* | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

### Estadística descriptiva
- Importante saber la naturaleza de los datos
- Valores máximos, mínimos, distribución, etc.

| Función | Descripción |
|:---------|:-----|
| *sum(arr)* | Suma de todos los elementos de *arr* |
| *mean(arr)* | Media aritmética de los elementos de *arr* |
| *std(arr)* | Desviación estándar de los elementos de *arr* |
| *cumsum(arr)* | Devuelve array con la suma acumulada de cada elementos con todos los anteriores |
| *cumprod(arr)* | Devuelve array con el producto acumulado de cada elementos con todos los anteriores |
| *min(arr), max(arr)* | Mínimo y máximo de *arr* |
| *any(arr)* | En array de tipo *bool*, retorna *True* si algún elemento es *True* |
| *all(arr)* | En array de tipo *bool*, retorna *True* si todos los elementos son *True* (o >0 en valores numéricos) |
| *unique(arr)* | Devuelve un array con valores únicos |
| *in1d(arr1, arr2)* | Devuelve un array con bool indicando si cada elemento de *arr1* está en *arr2* |
| *union1d(arr1, arr2)* | Devuelve la unión de ambos arrays |
| *intersect1d(arr1, arr2)* | Devuelve la intersección de ambos arrays |

### Álgebra lineal
- numpy.linalg contiene funciones para álgebra lineal
- dot product, multipliacción de matrices, cálculo del determinante, factorizaciones...

| Función | Descripción |
|:---------|:-----|
| *dot(mat1, mat2)* | Devuelve el producto escalar entre dos arrays. Si son matrices 2D, es equivalente a la multiplicación de ambas |
| *matmul(mat1, mat2)* | Devuelve el producto entre dos matrices |
| *trace(mat1, mat2)* | Suma de las diagonales de ambas matrices |
| *det(mat)* | Devuelve el determinante de la matriz |
| *eig(mat)* | Computa los autovalores y autovectores de la matriz cuadrada *mat* |
| *inv(mat)* | Devuelve la inversa de la matriz |
| *qr(mat)* | Computa la factorización QR de *mat* |
| *solve(A, b)* | Resuelve el sistema lineal de ecuaciones *Ax = b* para *b*, cuando *A* es una matriz cuadrada |